# Neuron Network - Lab

In [1]:
try:
    from google.colab import drive
    drive.mount('/content/drive')
except (ImportError, Exception):
    print("Local environment detected (KMUTT CPE342). Skipping Google Drive mount.")

Local environment detected (KMUTT CPE342). Skipping Google Drive mount.

### Part 1: Load  data

Import "bank-data.csv"

In [2]:
import pandas as pd
import os

data_path = 'bank-data.csv'
if not os.path.exists(data_path):
    data_path = '/content/drive/MyDrive/CPE_KMUTT/Year3/Semester_1-68/CPE342_MachineLearning/CPE342_Lab/CPE342_Lab_Assignment5_NeuralNetwork/bank-data.csv'
df = pd.read_csv(data_path, sep=';')
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4516,33,services,married,secondary,no,-333,yes,no,cellular,30,jul,329,5,-1,0,unknown,no
4517,57,self-employed,married,tertiary,yes,-3313,yes,yes,unknown,9,may,153,1,-1,0,unknown,no
4518,57,technician,married,secondary,no,295,no,no,cellular,19,aug,151,11,-1,0,unknown,no
4519,28,blue-collar,married,secondary,no,1137,no,no,cellular,6,feb,129,4,211,3,other,no
4520,44,entrepreneur,single,tertiary,no,1136,yes,yes,cellular,3,apr,345,2,249,7,other,no

### Part 2: Preprocess data

Preprocess the dataset as you have done before

#### 2.1 Binary encoding

Use LabelEncoder to encode the following columns:
- y
- default
- housing
- loan

In [3]:
from sklearn.preprocessing import LabelEncoder

# Create a LabelEncoder instance
le = LabelEncoder()
df['y'] = le.fit_transform(df['y'])
df['default'] = le.fit_transform(df['default'])
df['housing'] = le.fit_transform(df['housing'])
df['loan'] = le.fit_transform(df['loan'])
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,0,1787,0,0,cellular,19,oct,79,1,-1,0,unknown,0
1,33,services,married,secondary,0,4789,1,1,cellular,11,may,220,1,339,4,failure,0
2,35,management,single,tertiary,0,1350,1,0,cellular,16,apr,185,1,330,1,failure,0
3,30,management,married,tertiary,0,1476,1,1,unknown,3,jun,199,4,-1,0,unknown,0
4,59,blue-collar,married,secondary,0,0,1,0,unknown,5,may,226,1,-1,0,unknown,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4516,33,services,married,secondary,0,-333,1,0,cellular,30,jul,329,5,-1,0,unknown,0
4517,57,self-employed,married,tertiary,1,-3313,1,1,unknown,9,may,153,1,-1,0,unknown,0
4518,57,technician,married,secondary,0,295,0,0,cellular,19,aug,151,11,-1,0,unknown,0
4519,28,blue-collar,married,secondary,0,1137,0,0,cellular,6,feb,129,4,211,3,other,0
4520,44,entrepreneur,single,tertiary,0,1136,1,1,cellular,3,apr,345,2,249,7,other,0

#### 2.2 Convert categorical variables into dummy columns

(1) Use pd.get_dummies to convert the following categorical variales into dummy columns
- job
- maritial
- education
- contact
- month
- poutcome

(2) Drop columns that have been converted

In [4]:
# Apply get_dummies to the following categorical column
df = pd.get_dummies(df, columns=['job', 'marital', 'education', 'contact', 'month', 'poutcome'])
df

,age,default,balance,housing,loan,day,duration,campaign,pdays,previous,...,month_jun,month_mar,month_may,month_nov,month_oct,month_sep,poutcome_failure,poutcome_other,poutcome_success,poutcome_unknown
0,30,0,1787,0,0,19,79,1,-1,0,...,False,False,False,False,True,False,False,False,False,True
1,33,0,4789,1,1,11,220,1,339,4,...,False,False,True,False,False,False,True,False,False,False
2,35,0,1350,1,0,16,185,1,330,1,...,False,False,False,False,False,False,True,False,False,False
3,30,0,1476,1,1,3,199,4,-1,0,...,True,False,False,False,False,False,False,False,False,True
4,59,0,0,1,0,5,226,1,-1,0,...,False,False,True,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4516,33,0,-333,1,0,30,329,5,-1,0,...,False,False,False,False,False,False,False,False,False,True
4517,57,1,-3313,1,1,9,153,1,-1,0,...,False,False,True,False,False,False,False,False,False,True
4518,57,0,295,0,0,19,151,11,-1,0,...,False,False,False,False,False,False,False,False,False,True
4519,28,0,1137,0,0,6,129,4,211,3,...,False,False,False,False,False,False,False,True,False,False
4520,44,0,1136,1,1,3,345,2,249,7,...,False,False,False,False,False,False,False,True,False,False

#### 2.3 Train/Test separation

Perform hold-out method
- 60% training set
- 40% testing set

##### X/y separation

In [5]:
from sklearn.model_selection import train_test_split

X = df.drop('y', axis=1)
y = df['y']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

#### 2.4 Feature Scaling

It is always a good practice to scale the features so that all of them can be uniformly evaluated

In [6]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

## Artificial Neural Network : sklearn

### Part 3: Train a model

In [7]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)
mlp.fit(X_train, y_train)

MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)

### Part 4: Model Evaluation

Evaluation metrics
- confusion metrix
- accuracy
- precision, recall, f1-score

In [8]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

y_pred = mlp.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy: ', accuracy_score(y_test, y_pred))
print('Precision: ', precision_score(y_test, y_pred))
print('Recall: ', recall_score(y_test, y_pred))
print('F1-score: ', f1_score(y_test, y_pred))

[[1525   95]
 [ 115   74]]
Accuracy:  0.8839137645107794
Precision:  0.4378698224852071
Recall:  0.3915343915343915
F1-score:  0.4134078212290503

### Part 5: Model tuning

#### Note:

After building the classifier, try answering the following questions.

1. What is the Accuracy Score?
2. If you change your preprosessing method, can you improve the model?
3. If you change your parameters setting, can you improve the model?

In [9]:
# 1. What is the Accuracy Score?
print("=== Baseline MLPClassifier Evaluation ===")
print("Confusion Matrix:\n", cm)
print(f"Accuracy Score : {accuracy_score(y_test, y_pred):.4f}")
print(f"Precision Score: {precision_score(y_test, y_pred):.4f}")
print(f"Recall Score   : {recall_score(y_test, y_pred):.4f}")
print(f"F1-score       : {f1_score(y_test, y_pred):.4f}")

=== Baseline MLPClassifier Evaluation ===
Confusion Matrix:
 [[1525   95]
 [ 115   74]]
Accuracy Score : 0.8839
Precision Score: 0.4379
Recall Score   : 0.3915
F1-score       : 0.4134

#### 2. Preprocessing Method Comparison (StandardScaler vs. MinMaxScaler vs. RobustScaler)
Testing whether outlier handling or bounded feature scaling improves the decision boundary of MLPClassifier:

In [10]:
from sklearn.preprocessing import MinMaxScaler, RobustScaler

scalers = {
    'StandardScaler': StandardScaler(),
    'MinMaxScaler': MinMaxScaler(),
    'RobustScaler': RobustScaler()
}

print("=== Preprocessing Comparison ===")
for name, sc in scalers.items():
    X_tr = sc.fit_transform(X_train)
    X_te = sc.transform(X_test)
    m = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000, random_state=42)
    m.fit(X_tr, y_train)
    preds = m.predict(X_te)
    print(f"{name:15s} -> Accuracy: {accuracy_score(y_test, preds):.4f}, F1: {f1_score(y_test, preds):.4f}")

=== Preprocessing Comparison ===

StandardScaler  -> Accuracy: 0.8701, F1: 0.4169

MinMaxScaler    -> Accuracy: 0.8867, F1: 0.4730

RobustScaler    -> Accuracy: 0.8756, F1: 0.4094

#### 3. Parameter Tuning (Hidden Layers, Regularization, Early Stopping)
Experimenting with hidden layer topologies, Adam optimization, and L2 regularization:

In [11]:
param_configs = [
    {'name': 'Baseline (10, 10, 10)', 'hidden': (10, 10, 10), 'alpha': 0.0001, 'early_stopping': False},
    {'name': 'Deeper (64, 32)', 'hidden': (64, 32), 'alpha': 0.0001, 'early_stopping': False},
    {'name': 'Deeper (100, 50, 25)', 'hidden': (100, 50, 25), 'alpha': 0.001, 'early_stopping': False},
    {'name': 'Tuned (64, 32) + Reg + EarlyStop', 'hidden': (64, 32), 'alpha': 0.01, 'early_stopping': True},
]

print("=== Model Parameter Tuning ===")
for cfg in param_configs:
    clf = MLPClassifier(hidden_layer_sizes=cfg['hidden'], alpha=cfg['alpha'],
                        early_stopping=cfg['early_stopping'], max_iter=1000, random_state=42)
    clf.fit(X_train, y_train)
    preds = clf.predict(X_test)
    print(f"{cfg['name']:35s} -> Accuracy: {accuracy_score(y_test, preds):.4f}, F1: {f1_score(y_test, preds):.4f}")

=== Model Parameter Tuning ===

Baseline (10, 10, 10)               -> Accuracy: 0.8701, F1: 0.4169

Deeper (64, 32)                     -> Accuracy: 0.8795, F1: 0.4044

Deeper (100, 50, 25)                -> Accuracy: 0.8778, F1: 0.4260

Tuned (64, 32) + Reg + EarlyStop    -> Accuracy: 0.8972, F1: 0.4529

## Artificial Neural Network : keras
- See https://keras.io

Fitting a logistic regression model

### Part 3: Train a model

In [12]:
import keras; print(keras.__version__)

3.15.1

In [13]:
from keras import models
from keras import layers

In [14]:
X_train.shape

(2712, 48)

In [15]:
nn = models.Sequential()
nn.add(layers.Dense(48,activation = 'linear',input_shape=(None,48)))
nn.add(layers.Dense(1,activation = 'sigmoid'))

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [16]:
nn.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [17]:
nn.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, None, 48)       │         2,352 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, None, 1)        │            49 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,401 (9.38 KB)

 Trainable params: 2,401 (9.38 KB)

 Non-trainable params: 0 (0.00 B)

In [18]:
import numpy as np
X_train_add = np.expand_dims(X_train, axis=0)
y_train_add = np.expand_dims(y_train, axis=0)

In [19]:
history = nn.fit(X_train_add,y_train_add,epochs=100)

Epoch 1/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 423ms/step - accuracy: 0.4395 - loss: 0.8402

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 438ms/step - accuracy: 0.4395 - loss: 0.8402

Epoch 2/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.4440 - loss: 0.8323

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.4440 - loss: 0.8323

Epoch 3/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.4528 - loss: 0.8245

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.4528 - loss: 0.8245

Epoch 4/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.4598 - loss: 0.8169

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.4598 - loss: 0.8169

Epoch 5/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.4609 - loss: 0.8095

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.4609 - loss: 0.8095

Epoch 6/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.4668 - loss: 0.8022

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.4668 - loss: 0.8022

Epoch 7/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.4742 - loss: 0.7951

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.4742 - loss: 0.7951

Epoch 8/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.4782 - loss: 0.7881

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.4782 - loss: 0.7881

Epoch 9/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.4845 - loss: 0.7813

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.4845 - loss: 0.7813

Epoch 10/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.4886 - loss: 0.7746

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.4886 - loss: 0.7746

Epoch 11/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.4934 - loss: 0.7681

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - accuracy: 0.4934 - loss: 0.7681

Epoch 12/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - accuracy: 0.4993 - loss: 0.7617

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - accuracy: 0.4993 - loss: 0.7617

Epoch 13/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5055 - loss: 0.7555

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5055 - loss: 0.7555

Epoch 14/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.5107 - loss: 0.7493

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5107 - loss: 0.7493

Epoch 15/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.5177 - loss: 0.7433

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5177 - loss: 0.7433

Epoch 16/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5232 - loss: 0.7375

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5232 - loss: 0.7375

Epoch 17/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5295 - loss: 0.7317

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5295 - loss: 0.7317

Epoch 18/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.5358 - loss: 0.7260

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - accuracy: 0.5358 - loss: 0.7260

Epoch 19/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.5417 - loss: 0.7205

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - accuracy: 0.5417 - loss: 0.7205

Epoch 20/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.5516 - loss: 0.7151

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5516 - loss: 0.7151

Epoch 21/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.5564 - loss: 0.7097

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5564 - loss: 0.7097

Epoch 22/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.5623 - loss: 0.7045

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5623 - loss: 0.7045

Epoch 23/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5667 - loss: 0.6994

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5667 - loss: 0.6994

Epoch 24/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.5723 - loss: 0.6944

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5723 - loss: 0.6944

Epoch 25/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5771 - loss: 0.6894

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5771 - loss: 0.6894

Epoch 26/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.5874 - loss: 0.6846

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5874 - loss: 0.6846

Epoch 27/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5959 - loss: 0.6798

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5959 - loss: 0.6798

Epoch 28/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6044 - loss: 0.6752

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6044 - loss: 0.6752

Epoch 29/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6114 - loss: 0.6706

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6114 - loss: 0.6706

Epoch 30/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6198 - loss: 0.6661

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6198 - loss: 0.6661

Epoch 31/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6272 - loss: 0.6617

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6272 - loss: 0.6617

Epoch 32/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6346 - loss: 0.6573

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6346 - loss: 0.6573

Epoch 33/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6409 - loss: 0.6530

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6409 - loss: 0.6530

Epoch 34/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6464 - loss: 0.6489

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6464 - loss: 0.6489

Epoch 35/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6519 - loss: 0.6447

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6519 - loss: 0.6447

Epoch 36/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6611 - loss: 0.6407

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6611 - loss: 0.6407

Epoch 37/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6700 - loss: 0.6367

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6700 - loss: 0.6367

Epoch 38/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6766 - loss: 0.6328

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6766 - loss: 0.6328

Epoch 39/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6836 - loss: 0.6289

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6836 - loss: 0.6289

Epoch 40/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6940 - loss: 0.6251

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6940 - loss: 0.6251

Epoch 41/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7002 - loss: 0.6214

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7002 - loss: 0.6214

Epoch 42/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7065 - loss: 0.6177

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7065 - loss: 0.6177

Epoch 43/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7113 - loss: 0.6141

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7113 - loss: 0.6141

Epoch 44/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7201 - loss: 0.6105

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.7201 - loss: 0.6105

Epoch 45/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7253 - loss: 0.6070

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7253 - loss: 0.6070

Epoch 46/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7334 - loss: 0.6036

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7334 - loss: 0.6036

Epoch 47/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7393 - loss: 0.6002

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.7393 - loss: 0.6002

Epoch 48/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7452 - loss: 0.5968

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.7452 - loss: 0.5968

Epoch 49/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7500 - loss: 0.5936

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7500 - loss: 0.5936

Epoch 50/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7574 - loss: 0.5903

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7574 - loss: 0.5903

Epoch 51/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7600 - loss: 0.5871

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7600 - loss: 0.5871

Epoch 52/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7647 - loss: 0.5840

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7647 - loss: 0.5840

Epoch 53/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7673 - loss: 0.5809

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7673 - loss: 0.5809

Epoch 54/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7725 - loss: 0.5778

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.7725 - loss: 0.5778

Epoch 55/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7765 - loss: 0.5748

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7765 - loss: 0.5748

Epoch 56/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7777 - loss: 0.5718

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7777 - loss: 0.5718

Epoch 57/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7821 - loss: 0.5689

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7821 - loss: 0.5689

Epoch 58/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7858 - loss: 0.5660

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7858 - loss: 0.5660

Epoch 59/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7891 - loss: 0.5631

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7891 - loss: 0.5631

Epoch 60/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7909 - loss: 0.5603

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.7909 - loss: 0.5603

Epoch 61/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7961 - loss: 0.5575

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.7961 - loss: 0.5575

Epoch 62/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7983 - loss: 0.5548

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.7983 - loss: 0.5548

Epoch 63/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8009 - loss: 0.5521

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8009 - loss: 0.5521

Epoch 64/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8035 - loss: 0.5494

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8035 - loss: 0.5494

Epoch 65/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8068 - loss: 0.5468

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8068 - loss: 0.5468

Epoch 66/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8116 - loss: 0.5442

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8116 - loss: 0.5442

Epoch 67/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8145 - loss: 0.5417

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.8145 - loss: 0.5417

Epoch 68/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8175 - loss: 0.5391

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8175 - loss: 0.5391

Epoch 69/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8208 - loss: 0.5366

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8208 - loss: 0.5366

Epoch 70/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8230 - loss: 0.5342

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8230 - loss: 0.5342

Epoch 71/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8256 - loss: 0.5317

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8256 - loss: 0.5317

Epoch 72/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8271 - loss: 0.5293

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8271 - loss: 0.5293

Epoch 73/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8289 - loss: 0.5270

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8289 - loss: 0.5270

Epoch 74/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8315 - loss: 0.5246

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8315 - loss: 0.5246

Epoch 75/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8337 - loss: 0.5223

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8337 - loss: 0.5223

Epoch 76/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8352 - loss: 0.5200

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8352 - loss: 0.5200

Epoch 77/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8367 - loss: 0.5178

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8367 - loss: 0.5178

Epoch 78/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8378 - loss: 0.5156

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8378 - loss: 0.5156

Epoch 79/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8381 - loss: 0.5134

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8381 - loss: 0.5134

Epoch 80/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8400 - loss: 0.5112

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8400 - loss: 0.5112

Epoch 81/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8418 - loss: 0.5090

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8418 - loss: 0.5090

Epoch 82/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8429 - loss: 0.5069

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8429 - loss: 0.5069

Epoch 83/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8448 - loss: 0.5048

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8448 - loss: 0.5048

Epoch 84/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8451 - loss: 0.5027

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8451 - loss: 0.5027

Epoch 85/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8459 - loss: 0.5007

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.8459 - loss: 0.5007

Epoch 86/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8459 - loss: 0.4987

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.8459 - loss: 0.4987

Epoch 87/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8466 - loss: 0.4967

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8466 - loss: 0.4967

Epoch 88/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8481 - loss: 0.4947

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8481 - loss: 0.4947

Epoch 89/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8485 - loss: 0.4927

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8485 - loss: 0.4927

Epoch 90/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8485 - loss: 0.4908

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8485 - loss: 0.4908

Epoch 91/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8510 - loss: 0.4889

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8510 - loss: 0.4889

Epoch 92/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8521 - loss: 0.4870

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8521 - loss: 0.4870

Epoch 93/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8521 - loss: 0.4851

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8521 - loss: 0.4851

Epoch 94/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8529 - loss: 0.4833

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8529 - loss: 0.4833

Epoch 95/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8532 - loss: 0.4814

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8532 - loss: 0.4814

Epoch 96/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8544 - loss: 0.4796

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8544 - loss: 0.4796

Epoch 97/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8566 - loss: 0.4778

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.8566 - loss: 0.4778

Epoch 98/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.8580 - loss: 0.4761

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.8580 - loss: 0.4761

Epoch 99/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8595 - loss: 0.4743

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.8595 - loss: 0.4743

Epoch 100/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8610 - loss: 0.4726

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8610 - loss: 0.4726

### Part 4: Model Evaluation

In [20]:
X_test_add = np.expand_dims(X_test, axis=0)
y_test_add = np.expand_dims(y_test, axis=0)

In [21]:
test_loss, test_acc = nn.evaluate(X_test_add, y_test_add)
print('Test Loss: %s\nTest Accuracy: %s' % (test_loss,test_acc))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 0.8662 - loss: 0.4591

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step - accuracy: 0.8662 - loss: 0.4591

Test Loss: 0.45906102657318115
Test Accuracy: 0.8662244081497192

In [22]:
history.history

{'accuracy': [0.4395280182361603,
  0.4439527988433838,
  0.4528023600578308,
  0.45980826020240784,
  0.4609144628047943,
  0.46681416034698486,
  0.47418880462646484,
  0.4782448410987854,
  0.4845132827758789,
  0.48856931924819946,
  0.4933628439903259,
  0.4992625415325165,
  0.5055309534072876,
  0.5106931924819946,
  0.517699122428894,
  0.5232300758361816,
  0.5294985175132751,
  0.5357669591903687,
  0.5416666865348816,
  0.5516223907470703,
  0.5564159154891968,
  0.5623156428337097,
  0.5667403936386108,
  0.5722714066505432,
  0.5770648717880249,
  0.5873894095420837,
  0.5958701968193054,
  0.6043510437011719,
  0.6113569140434265,
  0.619837760925293,
  0.627212405204773,
  0.6345870494842529,
  0.6408554315567017,
  0.646386444568634,
  0.6519173979759216,
  0.6611356735229492,
  0.6699852347373962,
  0.6766223907470703,
  0.6836283206939697,
  0.6939527988433838,
  0.7002212405204773,
  0.7064896821975708,
  0.7112832069396973,
  0.7201327681541443,
  0.7252950072288513,
  0.7334070801734924,
  0.7393068075180054,
  0.7452064752578735,
  0.75,
  0.75737464427948,
  0.7599557638168335,
  0.76474928855896,
  0.7673304080963135,
  0.7724926471710205,
  0.7765486836433411,
  0.7776548862457275,
  0.7820796370506287,
  0.7857669591903687,
  0.7890855669975281,
  0.7909291982650757,
  0.7960914373397827,
  0.7983038425445557,
  0.8008849620819092,
  0.8034660816192627,
  0.8067846894264221,
  0.8115781545639038,
  0.8145280480384827,
  0.8174778819084167,
  0.8207964897155762,
  0.8230088353157043,
  0.8255899548530579,
  0.8270648717880249,
  0.8289085626602173,
  0.8314896821975708,
  0.8337020874023438,
  0.8351770043373108,
  0.8366519212722778,
  0.8377581238746643,
  0.8381268382072449,
  0.8399705290794373,
  0.8418141603469849,
  0.8429203629493713,
  0.844763994216919,
  0.8451327681541443,
  0.8458701968193054,
  0.8458701968193054,
  0.8466076850891113,
  0.8480826020240784,
  0.8484513163566589,
  0.8484513163566589,
  0.8510324358940125,
  0.8521386384963989,
  0.8521386384963989,
  0.8528761267662048,
  0.8532448410987854,
  0.8543510437011719,
  0.8565634489059448,
  0.8580383658409119,
  0.8595132827758789,
  0.860988199710846],
 'loss': [0.8402148485183716,
  0.8322685360908508,
  0.8244985342025757,
  0.8168999552726746,
  0.8094679713249207,
  0.8021977543830872,
  0.7950848937034607,
  0.7881250977516174,
  0.7813137173652649,
  0.7746465802192688,
  0.7681196928024292,
  0.7617290019989014,
  0.7554708123207092,
  0.7493411302566528,
  0.7433364391326904,
  0.737453043460846,
  0.7316877245903015,
  0.7260369062423706,
  0.7204974293708801,
  0.7150663733482361,
  0.709740400314331,
  0.7045166492462158,
  0.6993921995162964,
  0.6943644881248474,
  0.6894305944442749,
  0.6845881938934326,
  0.6798344850540161,
  0.6751672625541687,
  0.6705840826034546,
  0.6660826802253723,
  0.6616607904434204,
  0.6573163270950317,
  0.6530473828315735,
  0.6488515734672546,
  0.6447275280952454,
  0.6406728029251099,
  0.6366860866546631,
  0.6327653527259827,
  0.6289089322090149,
  0.6251152753829956,
  0.6213826537132263,
  0.6177098751068115,
  0.6140950322151184,
  0.6105369925498962,
  0.6070342659950256,
  0.6035856008529663,
  0.6001895666122437,
  0.5968449711799622,
  0.5935505628585815,
  0.5903052091598511,
  0.5871078372001648,
  0.5839572548866272,
  0.5808523893356323,
  0.5777923464775085,
  0.5747758746147156,
  0.5718022584915161,
  0.5688703656196594,
  0.5659794807434082,
  0.5631284713745117,
  0.5603166222572327,
  0.5575429797172546,
  0.5548070669174194,
  0.5521079301834106,
  0.5494444966316223,
  0.5468164086341858,
  0.5442230105400085,
  0.5416631698608398,
  0.5391365885734558,
  0.5366424918174744,
  0.5341802835464478,
  0.5317493677139282,
  0.5293489098548889,
  0.5269787311553955,
  0.524637758731842,
  0.5223259329795837,
  0.5200424790382385,
  0.5177868604660034,
  0.5155585408210754,
  0.5133572220802307,
  0.5111820697784424,
  0.5090330243110657,
  0.5069093108177185,
  0.504810631275177,
  0.5027365684509277,
  0.500686526298523,
  0.4986603856086731,
  0.49665746092796326,
  0.49467748403549194,
  0.4927200376987457,
  0.4907848536968231,
  0.48887133598327637,
  0.48697933554649353,
  0.48510846495628357,
  0.48325827717781067,
  0.4814285635948181,
  0.47961893677711487,
  0.4778292179107666,
  0.47605887055397034,
  0.474307656288147,
  0.472575306892395]}

### Part 5: Model tuning

#### Note:

After building the classifier, try answering the following questions.

1. What is the Accuracy Score?
2. If you change your preprosessing method, can you improve the model?
3. If you change your parameters setting, can you improve the model?

### Keras Model Tuning & Evaluation Answers

**1. What is the Accuracy Score?**
The baseline Keras logistic regression model achieves the accuracy printed below.

**2. Preprocessing & Batching Enhancements:**
Using 2D feature tensors directly with standard mini-batch training (`batch_size=64`) rather than expanding to 3D shape `(1, N, D)` improves vectorization and GPU/CPU cache efficiency.

**3. Hyperparameter & Architecture Tuning:**
Adding non-linear hidden layers (`Dense(64, relu)` + `Dense(32, relu)`), `Dropout(0.2)` for regularization, and the `Adam` optimizer provides substantial performance gains.

In [23]:
# Keras Model Tuning: Deep Neural Network Architecture
import keras
from keras import layers, models, optimizers

print(f"Baseline Keras Model Accuracy: {test_acc:.4f} (Loss: {test_loss:.4f})")

tuned_nn = models.Sequential([
    layers.Input(shape=(48,)),
    layers.Dense(64, activation='relu'),
    layers.Dropout(0.2),
    layers.Dense(32, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

tuned_nn.compile(
    optimizer=optimizers.Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

tuned_nn.summary()

tuned_history = tuned_nn.fit(
    X_train, y_train,
    epochs=30,
    batch_size=64,
    validation_split=0.2,
    verbose=1
)

tuned_loss, tuned_acc = tuned_nn.evaluate(X_test, y_test, verbose=0)
print(f"\n=== Final Keras Comparison ===")
print(f"Baseline Model Accuracy: {test_acc:.4f}")
print(f"Tuned DNN Model Accuracy: {tuned_acc:.4f}")
print(f"Improvement: +{(tuned_acc - test_acc)*100:.2f}%")

Baseline Keras Model Accuracy: 0.8662 (Loss: 0.4591)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 64)             │         3,136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,249 (20.50 KB)

 Trainable params: 5,249 (20.50 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/30

 1/34 ━━━━━━━━━━━━━━━━━━━━ 31s 953ms/step - accuracy: 0.4062 - loss: 0.7677

34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.7948 - loss: 0.5242 - val_accuracy: 0.8895 - val_loss: 0.3767

Epoch 2/30

 1/34 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8125 - loss: 0.4664

34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8746 - loss: 0.3765 - val_accuracy: 0.8895 - val_loss: 0.3211

Epoch 3/30

 1/34 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8750 - loss: 0.3988

34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8755 - loss: 0.3339 - val_accuracy: 0.8950 - val_loss: 0.2893

Epoch 4/30

 1/34 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8594 - loss: 0.2842

34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8764 - loss: 0.3031 - val_accuracy: 0.8969 - val_loss: 0.2679

Epoch 5/30

 1/34 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8906 - loss: 0.2988

34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8815 - loss: 0.2789 - val_accuracy: 0.9006 - val_loss: 0.2554

Epoch 6/30

 1/34 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8594 - loss: 0.2897

34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8884 - loss: 0.2551 - val_accuracy: 0.9006 - val_loss: 0.2474

Epoch 7/30

 1/34 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8438 - loss: 0.3115

34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8949 - loss: 0.2379 - val_accuracy: 0.8987 - val_loss: 0.2447

Epoch 8/30

 1/34 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9219 - loss: 0.2166

34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9023 - loss: 0.2309 - val_accuracy: 0.9006 - val_loss: 0.2436

Epoch 9/30

 1/34 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9062 - loss: 0.2386

34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9092 - loss: 0.2249 - val_accuracy: 0.8969 - val_loss: 0.2430

Epoch 10/30

 1/34 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9531 - loss: 0.1804

34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9124 - loss: 0.2142 - val_accuracy: 0.8950 - val_loss: 0.2432

Epoch 11/30

 1/34 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9062 - loss: 0.2961

34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9119 - loss: 0.2094 - val_accuracy: 0.8950 - val_loss: 0.2452

Epoch 12/30

 1/34 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9531 - loss: 0.1928

34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9161 - loss: 0.2030 - val_accuracy: 0.8950 - val_loss: 0.2496

Epoch 13/30

 1/34 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9375 - loss: 0.2076

34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9230 - loss: 0.1987 - val_accuracy: 0.8932 - val_loss: 0.2510

Epoch 14/30

 1/34 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9375 - loss: 0.1533

34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9239 - loss: 0.1941 - val_accuracy: 0.8950 - val_loss: 0.2549

Epoch 15/30

 1/34 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9688 - loss: 0.1005

34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9281 - loss: 0.1827 - val_accuracy: 0.8969 - val_loss: 0.2562

Epoch 16/30

 1/34 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9688 - loss: 0.1121

34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9225 - loss: 0.1892 - val_accuracy: 0.8969 - val_loss: 0.2570

Epoch 17/30

 1/34 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9375 - loss: 0.1279

34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9276 - loss: 0.1797 - val_accuracy: 0.8969 - val_loss: 0.2621

Epoch 18/30

 1/34 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8438 - loss: 0.3020

34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9285 - loss: 0.1743 - val_accuracy: 0.8932 - val_loss: 0.2609

Epoch 19/30

 1/34 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9531 - loss: 0.1284

34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9304 - loss: 0.1695 - val_accuracy: 0.8932 - val_loss: 0.2652

Epoch 20/30

 1/34 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9531 - loss: 0.1092

34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9313 - loss: 0.1672 - val_accuracy: 0.8932 - val_loss: 0.2665

Epoch 21/30

 1/34 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9688 - loss: 0.1431

34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.1628 - val_accuracy: 0.8913 - val_loss: 0.2700

Epoch 22/30

 1/34 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9375 - loss: 0.1311

34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9373 - loss: 0.1601 - val_accuracy: 0.8913 - val_loss: 0.2762

Epoch 23/30

 1/34 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9219 - loss: 0.1953

34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9345 - loss: 0.1619 - val_accuracy: 0.8858 - val_loss: 0.2755

Epoch 24/30

 1/34 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9844 - loss: 0.0617

34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9410 - loss: 0.1538 - val_accuracy: 0.8895 - val_loss: 0.2771

Epoch 25/30

 1/34 ━━━━━━━━━━━━━━━━━━━━ 2s 73ms/step - accuracy: 0.9531 - loss: 0.1187

34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9391 - loss: 0.1484 - val_accuracy: 0.8858 - val_loss: 0.2829

Epoch 26/30

 1/34 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8906 - loss: 0.1952

34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9373 - loss: 0.1526 - val_accuracy: 0.8895 - val_loss: 0.2832

Epoch 27/30

 1/34 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9062 - loss: 0.1718

34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9465 - loss: 0.1463 - val_accuracy: 0.8858 - val_loss: 0.2899

Epoch 28/30

 1/34 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9375 - loss: 0.1408

34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9410 - loss: 0.1420 - val_accuracy: 0.8858 - val_loss: 0.2893

Epoch 29/30

 1/34 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9375 - loss: 0.1557

34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9433 - loss: 0.1420 - val_accuracy: 0.8913 - val_loss: 0.2883

Epoch 30/30

 1/34 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9375 - loss: 0.1260

34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9424 - loss: 0.1371 - val_accuracy: 0.8913 - val_loss: 0.2860

=== Final Keras Comparison ===
Baseline Model Accuracy: 0.8662
Tuned DNN Model Accuracy: 0.9033
Improvement: +3.70%